/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.69
 * Generated at: 2021-07-16 08:02:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import beans.*;

public final class ex07_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("beans");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- 관련 class import -->\r\n");
      out.write("\r\n");
      out.write("<!-- 자바빈 연결, 현재는 위에 beans 패키지 안에 RegisterMgr이 있다보니 할 필요가 없다. -->\r\n");
      beans.RegisterMgr regMgr = null;
      regMgr = (beans.RegisterMgr) _jspx_page_context.getAttribute("regMgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (regMgr == null){
        regMgr = new beans.RegisterMgr();
        _jspx_page_context.setAttribute("regMgr", regMgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>useBean을 사용한 데이터베이스 연동</title>\r\n");
      out.write("<!-- 부트스트랩 연결 -->\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 사용자 정의 css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style3.css\" type=\"text/css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1 class=\"text-center\">전체 레코드 조회</h1>\r\n");
      out.write("<hr />\r\n");
      out.write("	\r\n");
      out.write("	<table  class=\"table table-dark table-striped\" style=\"width.80%; margin:20px auto\">\r\n");
      out.write("		<thead>\r\n");
      out.write("		<tr><td colspan=\"5\" style=\"text-align:right\"><a href=\"ex07_form.jsp\" class=\"btn3 btn-secondary\">레코드 추가</a></td></tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th class=\"text-center\">아이디</th>\r\n");
      out.write("			<th class=\"text-center\">이름</th>\r\n");
      out.write("			<th class=\"text-center\">더 보기</th>\r\n");
      out.write("			<th class=\"text-center\">삭제</th>\r\n");
      out.write("			<th class=\"text-center\">수정</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tbody>\r\n");
      out.write("		");

		// DB 테이블의 전체레코드를 벡터에 저장
		// 벡터 참조 변수에 getRegisterList() 호출해서 저장
		// Vector<자바빈클래스명> 참조변수 = DAO식별자.메서드명()
		Vector<RegisterBean> vlist = regMgr.getRegisterList();
		// 레코드 총 갯수
		int counter = vlist.size();
		// RegisterBean 자바빈 각 레코드 반환
		for (int i = 0; i < vlist.size(); i++) {
			// RegisterBean bean = (RegisterBean)vlist.elementAt(i);
			RegisterBean bean = vlist.get(i);
		
      out.write("\r\n");
      out.write("		<!-- 테이블 행으로 html방식으로 출력 -->\r\n");
      out.write("		<!-- 전에 배운 방법으로 try catch 구문을 가져와서 out.println안에서 th, tr을 사용하여 rs.get을 이용하여 받을 수도 있다. -->\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td class=\"text-center\">");
      out.print(bean.getUserId());
      out.write("</td>\r\n");
      out.write("			<td class=\"text-center\">");
      out.print(bean.getName());
      out.write("</td>\r\n");
      out.write("			<!-- ex08_info.jsp?userId=bean.getUserId() -->\r\n");
      out.write("			<td class=\"text-center\"><a href=\"ex07_info.jsp?userId=");
      out.print(bean.getUserId());
      out.write(" \"class=\"btn btn-dark\">더 보기</a></td>\r\n");
      out.write("			<td class=\"text-center\"><a href=\"ex07_delete.jsp?userId=");
      out.print(bean.getUserId());
      out.write(" \"class=\"btn2 btn-dark\">삭제</a></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		} // for ending
		
      out.write("\r\n");
      out.write("		</tbody>\r\n");
      out.write("	</table>\r\n");
      out.write("	<p class=\"text-center\">total records :	");
      out.print( counter );
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
